### PR TITLE
Added prime_checker.jl mini project

### PR DESCRIPTION
**Pull request by mertbozkir**
PrimeChecker takes number input and returns whether it's a prime number or not.  🤘

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Thank you for this! A few things: 
- [ ] Can you add comments on the code for clarity, whatever you think a new user might need to know
- [ ] Please update the code to have consistent spacing
- [ ] Use lowercase file names and "_"'s between the words
- [ ] Add this to the list of problems in the README

Thanks for adding this and happy to merge after these are addressed

**Comment by logankilpatrick** [comment]
Please also think of a good emoji to use with the problem for the README, maybe: 🔢

**Comment by mertbozkir** [comment]
Okay, Logan. I am fixing right now.

**Comment by mertbozkir** [comment]
- [x] Added comments to clarify what is project structure. f85b7041dc3f632c71f88c30b430b356e8122341
- [x] Deleted spacing in function d2d53786a47a8493e329fd3e54ea020d61412c55
- [x] Changed file_name with base on contribution rules -same commit with first one f85b7041dc3f632c71f88c30b430b356e8122341
- [x] Added readme and resolved-conflicts 9939f9835590fc90f992e4b41ffa8e2b9c332d4c

Also, it is the 10th project in this repo 🎯

**Review by logankilpatrick — APPROVED** [review]

**Comment by logankilpatrick** [comment]
Thank you for this!!

**Pull request merged**
